services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: .env.dev
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Ecommerce.settings
      
    prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
