global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ipswich_retail:8000']  # replace with your Django service name and port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
