global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ipswichretail-production.up.railway.app']  # replace with your Django service name and port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
remote_write:
  - url: https://prometheus-prod-55-prod-gb-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 2681485
      password: "${GRAFANA_API_KEY}"