name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u mohammadrizwan007 --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/mohammadrizwan007/ipswich_retail:latest .
        # run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/mohammadrizwan007/ipswich_retail:latest
        # run: docker push ghcr.io/${{ github.repository }}:latest
